hostname: localhost3
baseurl: "http://localhost3:1010"
language: en
template:
  engine: pebble
modules:
  active:
    - pebble-module
content:
  pipeline:
    - markdown
    - shortcode
    - template