id: demo-site
context_path: "/de"
hostname: 
  - localhost
  - localhost1
baseurl: "http://localhost:1010/de"
language: en
test: Hallo1
markdown:
  engine: markedjs
theme: default
modules:
  active:
    - markedjs-module
    - seo-module
    - forms-module
media:
  formats:
    - name: small
      width: 256
      height: 256
      format: webp
      compression: true
    - name: big
      width: 512
      height: 512
      format: webp
      compression: true
    - name: test2
      width: 72
      height: 72
      format: webp
      compression: true