id: feature-site-de
context_path: "/de"
hostname: 
  - localhost2
baseurl: "http://localhost2:1010/de/"
language: en
test: Hallo1
markdown:
  engine: markedjs
theme: test
modules:
  active:
    - markedjs-module
    - seo-module
    - forms-module
media:
  formats:
    - name: small
      width: 256
      height: 256
      format: webp
      compression: true
    - name: big
      width: 512
      height: 512
      format: webp
      compression: true
    - name: test2
      width: 72
      height: 72
      format: webp
      compression: true