hostname: localhost
baseurl: "https://demo.marx-software.de"
template:
  engine: thymeleaf
markdown:
  engine: markedjs
modules:
  active:
    - example-module
#    - flexmark-module
    - markedjs-module
    - pebble-module
    - thymeleaf-module
    - freemarker-module