hostname: localhost
template:
  engine: thymeleaf
markdown:
  engine: flexmark
modules:
  active:
    - example-module
    - flexmark-module
    - pebble-module
    - thymeleaf-module
    - freemarker-module