id: demo-site
hostname: 
  - localhost
  - localhost1
baseurl: "http://localhost:1010"
language: en
test: Hallo
markdown:
  engine: markedj
theme: default
modules:
  active:
    - markedj-module
    - seo-module
    - forms-module
    - example-module
media:
  formats:
    - name: small
      width: 256
      height: 256
      format: webp
      compression: true
    - name: big
      width: 512
      height: 512
      format: webp
      compression: true
    - name: test2
      width: 72
      height: 72
      format: webp
      compression: true