hostname: 
  - localhost
  - localhost1
baseurl: "http://localhost:1010"
language: en
markdown:
  engine: markedjs
theme: default
modules:
  active:
    - markedjs-module
media:
  formats:
    - name: small
      width: 256
      height: 256
      format: webp
      compression: true
    - name: big
      width: 512
      height: 512
      format: webp
      compression: true