hostname: localhost
baseurl: "http://localhost:8080"
language: en
template:
  engine: thymeleaf
markdown:
  engine: markedjs
modules:
  active:
    - example-module
#    - flexmark-module
    - markedjs-module
#    - pebble-module
    - thymeleaf-module
#    - freemarker-module
    - search-module