id: feature-site
hostname: 
  - localhost2
baseurl: "http://localhost2:1010"
language: en
test: Hallo
markdown:
  engine: markedj
theme: test
modules:
  active:
    - markedj-module
    - seo-module
    - forms-module
media:
  formats:
    - name: small
      width: 256
      height: 256
      format: webp
      compression: true
    - name: big
      width: 512
      height: 512
      format: webp
      compression: true
    - name: test2
      width: 72
      height: 72
      format: webp
      compression: true